[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
whitelist_token_sale_mint = "BiHgbT5QViTwpY658qAcgcTNuPYo2UZr2sjTwTF9JdbX"
whitelist_token_sale_vault = "4KSUrirLpTrGMmgKNCcXtv7wsJ2kdfPTZJdtU4k4ABHs"

[programs.devnet]
whitelist_token_sale_mint = "BiHgbT5QViTwpY658qAcgcTNuPYo2UZr2sjTwTF9JdbX"
whitelist_token_sale_vault = "4KSUrirLpTrGMmgKNCcXtv7wsJ2kdfPTZJdtU4k4ABHs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
